# Generated by Django 3.1.7 on 2021-02-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
