# Generated by Django 3.1.7 on 2021-02-27 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
